oro_menu_config:
    items:
        issues_tab:
            label: 'oro.issues.menu.issues_tab.label'
            uri: '#'
            extras:
                icon: icon-group
                position: 10

        issues_list_item:
            label: 'oro.issues.issue.list'
            route: oro_issue_index
        issue_create_item:
            label: 'oro.issues.issue.create'
            route: oro_issue_create


    tree:
        application_menu:
            children:
                issues_tab:
                    children:
                        issues_list_item: ~
                        issue_create_item: ~
