oro_menu_config:
    items:
        issues_tab:
            label: 'oro.issues.menu.issues_tab.label'
            uri: '#'
            extras:
                icon: icon-group
                position: 10

        issues_list_item:
            label: 'oro.issues.issue.list'
            route: oro_issue_index
        issue_create_item:
            label: 'oro.issues.issue.create'
            route: oro_issue_create


    tree:
        application_menu:
            children:
                issues_tab:
                    children:
                        issues_list_item: ~
                        issue_create_item: ~

oro_titles:
    oro_issue_index: 'oro.issues.issue.list'
    oro_issue_view: 'oro.issues.issue.view'
    oro_issue_create: 'oro.issues.issue.create'
    oro_issue_update: 'oro.issues.issue.update'
