placeholders:
    view_navButtons_before:
        items:
            issue_buttons:
                order: 100
items:
    issue_buttons:
        template: OroIssuesBundle:Widget:buttons.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'