definitions:
    update_issue_status:
        label:   Update issue status
        enabled: true
        order:   100
        entity:  Oro\Bundle\IssuesBundle\Entity\Issue
        actions_configuration:
            - @find_entity:
                conditions:
                    @empty: $status
                parameters:
                    class: Oro\Bundle\IssuesBundle\Entity\IssueStatus
                    attribute: $status
                    identifier: 'new'

    set_issue_reporter:
        label:   Set issue reporter
        enabled: true
        order:   100
        entity:  Oro\Bundle\IssuesBundle\Entity\Issue
        pre_conditions:
            @empty: $reporter
        actions_configuration:
            - @assign_active_user: $reporter

triggers:
    update_issue_status:
        -
            event: create
        -
            event: update
            field: status
            priority: 10
            queued: true
            time_shift: 1

    set_issue_reporter:
        -
            event: create