Oro\Bundle\IssuesBundle\Entity\Issue:
    alias:                          oro_issue
    label:                          oro.issues.issue.entity_plural_label
    title_fields:                   [summary,code]
    search_template:                OroIssuesBundle:Issue:searchResult.html.twig
    route:
        name:                       oro_issue_view
        parameters:
            id:                     id
    fields:
        -
            name:                   summary
            target_type:            text
        -
            name:                   code
            target_type:            text
        -
            name:                   description
            target_type:            text
        -
            name:                   type
            relation_type:          many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
        -
            name:                   status
            relation_type:          many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
        -
            name:                   priority
            relation_type:          many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
        -
            name:                   resolved
            relation_type:          many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
        -
            name:                   assignee
            relation_type:          many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
                -
                    name: firstName
                    target_type: text
                -
                    name: lastName
                    target_type: text
        -
            name:                   reporter
            relation_type:          many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
