Oro\Bundle\IssuesBundle\Entity\Issue:
    alias:                          oro_issue
    label:                          oro.issues.issue.entity_plural_label
    title_fields:                   [summary,code]
    search_template:                OroIssuesBundle:Issue:searchResult.html.twig
    route:
        name:                       oro_issue_view
        parameters:
            id:                     id
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   code
            target_type:            text
            target_fields:          [code]
        -
            name:                   description
            target_type:            text
            target_fields:          [description]