parameters:
    oro_issue.entity.class: Oro\Bundle\IssuesBundle\Entity\Issue
services:
#    oro_issues.example:
#        class: Oro\Bundle\IssuesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
