parameters:
    oro_issues.entity.class: Oro\Bundle\IssuesBundle\Entity\Issue
    oro_issues.issue.manager.class: Oro\Bundle\IssuesBundle\Entity\Manager\IssuesManager
    oro_issues.issue.form.type.class: Oro\Bundle\IssuesBundle\Form\Type\IssueType
    oro_issues.issue.form.type.api.class: Oro\Bundle\IssuesBundle\Form\Type\IssueApiType
    oro_issues.issue.form.handler.api.class: Oro\Bundle\IssuesBundle\Form\Handler\IssueHandler
    oro_issues.subscriber.issue_note.class: Oro\Bundle\IssuesBundle\EventListener\AddNoteSubscriber

services:
    oro_issues.issue.manager:
        class:                        '%oro_issues.issue.manager.class%'
        arguments:                    ['@doctrine.orm.entity_manager',]

    oro_issues.issue_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%oro_issues.entity.class%'
            - '@doctrine.orm.entity_manager'

    #Form Types
    oro_issues.form.type.issue:
        class: '%oro_issues.issue.form.type.class%'
        tags:
            - { name: form.type, alias: issue_type }

    oro_issues.form.type.issue.api:
        class: '%oro_issues.issue.form.type.api.class%'
        tags:
            - { name: form.type, alias: issue_type_api }

    #Form Instances
    oro_issues.form.issue:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [issue_type_form, issue_type]

    oro_issues.form.issue.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: [issue_type_form, issue_type_api]

    #Form Handler for API
    oro_issues.form.handler.issue.api:
        class: '%oro_issues.issue.form.handler.api.class%'
        scope: request
        arguments:
            - '@oro_issues.form.issue.api'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #Subscribers
    oro_issues.subscriber.issue_note:
        class: '%oro_issues.subscriber.issue_note.class%'
        tags:
            - { name: doctrine.event_subscriber }