parameters:
    oro_issues.entity.class: Oro\Bundle\IssuesBundle\Entity\Issue
    oro_issues.issue.manager.class: Oro\Bundle\IssuesBundle\Entity\Manager\IssuesManager

services:
    oro_issues.issue.manager:
        class:                        '%oro_issues.issue.manager.class%'
        arguments:                    ['@doctrine.orm.entity_manager',]
