Oro\Bundle\IssuesBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        code:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - NotBlank: ~
        type:
            - NotBlank: ~
        priority:
            - NotBlank: ~
        assignee:
            - NotBlank: ~

